# Generated by Django 3.0.8 on 2020-07-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронный адрес'),
        ),
    ]
